### ISSUE TITLE
Check wake-up-inactive.<mob>-max-per-tick

### ISSUE THREAD

**Issue by SrBedrock** [Pemigrade/botflop#8]
Check wake-up-inactive.\<mob>-max-per-tick before suggesting to decrease wake-up-inactive.\<mob>-for

Config Example:
```yml
      wake-up-inactive:
        animals-max-per-tick: 0
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 0
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 0
        villagers-every: 600
        villagers-for: 100
        flying-monsters-max-per-tick: 0
        flying-monsters-every: 200
        flying-monsters-for: 100
```

Suggestion:
![image](https://user-images.githubusercontent.com/51332006/104410189-945b1180-5546-11eb-8b54-afa1ed5e3146.png)
